In [2]:
import numpy as np


# 1. Create a 3x3x3 array with random values

In [4]:
np.random.random((3,3,3))

array([[[0.76821779, 0.81682614, 0.7299414 ],
        [0.35075986, 0.64359426, 0.61842322],
        [0.3222247 , 0.55012778, 0.44115278]],

       [[0.6241387 , 0.68175239, 0.72544886],
        [0.78138781, 0.27794032, 0.61735997],
        [0.53050363, 0.2640514 , 0.10301588]],

       [[0.78324291, 0.00457515, 0.15481201],
        [0.11449059, 0.76676644, 0.33425099],
        [0.31317503, 0.05336962, 0.38327429]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [5]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [8]:
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

# 5. How to find common values between two arrays?

In [9]:
a1=np.array([1,2,3,4,5,6])
a2=np.array([1,12,31,4,5,62])

In [10]:
np.intersect1d(a1,a2)

array([1, 4, 5])

# 6.How to get the dates of yesterday, today and tomorrow?

In [16]:
print("Today's Date:")
np.datetime64('today','D')

Today's Date:


numpy.datetime64('2020-08-01')

In [17]:
print("Yesterday's Date:")
np.datetime64('today','D')- np.timedelta64(1,'D')

Yesterday's Date:


numpy.datetime64('2020-07-31')

In [15]:
print("Tommorrow's Date:")
np.datetime64('today','D')+ np.timedelta64(1,'D')

Tommorrow's Date:


numpy.datetime64('2020-08-02')

# 7. Consider two random array A and B, check if they are equal

In [18]:
arr1=np.random.random((3,3))
arr2=np.random.random((3,3))

In [19]:
np.equal(arr1,arr2)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

# 8.Create random vector of size 10 and replace the maximum value by 0

In [25]:
 arr1=np.random.random((3,3))

In [26]:
arr1[arr1.argmax()]=10

In [27]:
arr1

array([[ 0.51270904,  0.1077569 ,  0.98874389],
       [ 0.59609297,  0.6848313 ,  0.24431969],
       [10.        , 10.        , 10.        ]])

# 9. How to print all the values of an array?

In [31]:
for(i in arr1):
    print(i)

SyntaxError: invalid syntax (<ipython-input-31-ae9c7b8ca042>, line 1)

# 10.Subtract the mean of each row of a matrix

In [37]:
 arr3= np.random.rand(2,3)
arr3

array([[0.60150547, 0.71569115, 0.78626658],
       [0.3341162 , 0.67545215, 0.75800755]])

In [34]:
arr3-arr3.mean()

array([[ 0.14463781,  0.24001569, -0.45508138],
       [ 0.19398225,  0.15918333, -0.28273771]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [6]:
v1 = np.ones(10)
v2 = np.random.randint(0,len(v1),20)
v2

array([9, 4, 3, 2, 8, 6, 4, 1, 3, 7, 0, 7, 2, 2, 1, 1, 0, 8, 2, 5])

In [7]:
v1 += np.bincount(v2, minlength=len(v1))
print(v1)

[3. 4. 5. 3. 3. 2. 2. 3. 3. 2.]


# 12.How to get the diagonal of a dot product?

In [12]:
v=np.random.randint(0,10,(4,3))
w=np.random.randint(0,10,(3,4))

In [14]:
print(v)
print(w)

[[2 6 4]
 [9 6 6]
 [5 1 5]
 [2 4 8]]
[[3 2 1 2]
 [1 0 6 0]
 [8 7 0 0]]


In [20]:
dotProduct=np.dot(v,w)
dotProduct

array([[44, 32, 38,  4],
       [81, 60, 45, 18],
       [56, 45, 11, 10],
       [74, 60, 26,  4]])

In [19]:
dotProduct.diagonal()

array([44, 60, 11,  4])

# 13.How to find the most frequent value in an array?

In [41]:
arr= np.random.randint(0,10,50)
arr

array([6, 0, 7, 4, 3, 9, 5, 6, 1, 4, 9, 6, 8, 4, 5, 7, 7, 8, 8, 0, 1, 6,
       5, 7, 8, 6, 8, 8, 1, 5, 8, 2, 0, 9, 5, 3, 4, 7, 5, 5, 9, 1, 5, 2,
       7, 1, 8, 1, 6, 7])

In [42]:
print('most frequent:', np.bincount(arr).argmax())

most frequent: 5


# 14.How to get the n largest values of an array

In [45]:
arr=np.arange(100000)
arr

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [48]:
n=4
print(arr[np.argsort(arr)[-n:]])

[99996 99997 99998 99999]


# 15.How to create a record array from a regular array?

-  to create arrays of structs 

In [49]:
arr = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
arr

array([['Hello', '2.5', '3'],
       ['World', '3.6', '2']], dtype='<U5')

In [50]:
recArr = np.core.records.fromarrays(arr.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')

In [52]:
print(recArr)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
